'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wucAyuda

    '''<summary>
    '''imbAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbAyuda As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''upnlAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlAyuda As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlEncabezadoAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEncabezadoAyuda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imbInicioAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbInicioAyuda As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbIndiceAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbIndiceAyuda As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtBuscarAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuscarAyuda As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBuscarAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarAyuda As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblInicioAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInicioAyuda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIndiceAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndiceAyuda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuscarAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuscarAyuda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlContenidoAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlContenidoAyuda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlInicioAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInicioAyuda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTituloInicioAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloInicioAyuda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContenidoInicioAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContenidoInicioAyuda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlIndice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIndice As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblIndice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trvIndice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trvIndice As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''pnlInformacionAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInformacionAyuda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lnbMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnbMenu As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMenu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnbSubmenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnbSubmenu As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSubmenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmenu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnbAyudaPadre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnbAyudaPadre As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblAyudaPadre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAyudaPadre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnbAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnbAyuda As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblTituloAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloAyuda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContenudoAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContenudoAyuda As Global.System.Web.UI.WebControls.Label
End Class
