'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wucNotificaciones

    '''<summary>
    '''divMensajeNotificacionUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMensajeNotificacionUsuario As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divmensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divmensaje As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMensajeNotificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeNotificacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnArchivo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEnterado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnterado As Global.System.Web.UI.WebControls.Button
End Class
