'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucAnexoModalRowOfi

    '''<summary>
    '''lblFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chk_Carpeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Carpeta As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_CD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_CD As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_Sobre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Sobre As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_Paq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Paq As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_Rev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Rev As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_Otro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Otro As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''imgOtros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgOtros As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hdn_CheckValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_CheckValues As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFolio As Global.System.Web.UI.WebControls.HiddenField
End Class
