'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AltaIrregularidadesVisita
    
    '''<summary>
    '''upnlConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlConsulta As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''divAltaIrregularidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAltaIrregularidades As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LblNumIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNumIrregularidad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFecIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecIrregularidad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''calExFechaIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calExFechaIrregularidad As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCal As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''LblProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProceso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProceso As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblSubProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSubProceso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlSubProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubProceso As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblConducta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConducta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlConducta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConducta As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIrregularidad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblComentarios As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtComentarios As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblIrregularidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblIrregularidades As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlBotones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBotones As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DivAltaIrreg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivAltaIrreg As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAgregarIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarIrregularidad As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivModificaIrregVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivModificaIrregVisita As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnModificarIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModificarIrregularidad As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelIrreg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelIrreg As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivBandejaIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivBandejaIrregularidad As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divReqInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReqInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvReqInformacVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReqInformacVisita As Global.CustomGridView.CustomGridView
    
    '''<summary>
    '''HiddenFieldIDIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldIDIrregularidad As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HiddenFieldSubProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldSubProceso As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HiddenFieldConducta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldConducta As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HiddenFieldIrregularidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldIrregularidad As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HiddenFieldModificar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldModificar As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HiddenFieldFolioVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldFolioVisita As Global.System.Web.UI.WebControls.HiddenField
End Class
