'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BandejaOficios
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''frmBandejaEntrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmBandejaEntrada As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Toolkitscriptmanager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Toolkitscriptmanager2 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''Controles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Controles As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''BtnPersonalizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPersonalizar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ID_OFICIO0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_OFICIO0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CLAVE_OFICIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLAVE_OFICIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TIPO_OFICIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TIPO_OFICIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FECHA_VENCIMIENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FECHA_VENCIMIENTO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PLAZO_DIAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PLAZO_DIAS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FECHA_NOTIFICACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FECHA_NOTIFICACION As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ENTIDAD_CORTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ENTIDAD_CORTO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ID_TIPO_DOCUMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_TIPO_DOCUMENTO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''F_FECHA_OFICIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_FECHA_OFICIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ID_CONSAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_CONSAR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ID_CLASIFICACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_CLASIFICACION As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''T_CLASIFICACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_CLASIFICACION As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''T_HYP_ARCHIVOSCAN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_HYP_ARCHIVOSCAN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ID_ENTIDAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_ENTIDAD As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ID_AREA_OFICIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_AREA_OFICIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ID_ANIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_ANIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''I_OFICIO_CONSECUTIVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I_OFICIO_CONSECUTIVO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NOTIFICACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NOTIFICACION As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Filtros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filtros As Global.SEPRIS.FiltroBusquedaOfi
    
    '''<summary>
    '''Imagen_procesando control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Imagen_procesando As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GRID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GRID As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPrincipal As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''tblControles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblControles As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''Boton_guardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Boton_guardar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnReasignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReasignar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnTurnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTurnar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnQuitarTurnado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitarTurnado As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAdjuntarSIE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdjuntarSIE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnChecks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnChecks As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''trBtnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBtnCancelar As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''updPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''PanelErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelErrores As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanelErroresHandle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelErroresHandle As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblErroresTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErroresTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErroresPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErroresPopup As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFecRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecRec As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFecDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDest As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRec As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRefere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefere As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRegistros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistros As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOficio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemitente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAtendidaStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtendidaStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAsunto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAsunto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponsable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaRegistro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaLimite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaLimite As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProvieneSIE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProvieneSIE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnModalOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnModalOk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnContinua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnContinua As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ModalPopupExtenderErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderErrores As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''lblErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrores As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''linkbotonArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkbotonArchivo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BotonInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BotonInicio As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCaptura As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''PanelCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCaptura As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanelCapturaHandel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCapturaHandel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblCapturaTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCapturaTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnCapturaOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCapturaOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnCapturaCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCapturaCancelar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ModalPopUpCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopUpCaptura As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''lnkProcesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProcesa As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlProcesando control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProcesando As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lnkCierra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCierra As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mpeProcesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeProcesa As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''btnLigar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLigar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image
End Class
