'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BandejaIrregularidades

    '''<summary>
    '''upnlIrregInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlIrregInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''gvReqInformac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReqInformac As Global.CustomGridView.CustomGridView

    '''<summary>
    '''hfSelectedValueRequerimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedValueRequerimiento As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTipoGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTipoGuardar As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFecEstEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFecEstEntrega As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFecRealEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFecRealEntrega As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIDRequerimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIDRequerimiento As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnAceptarM1B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarM1B1A As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAceptarM2B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarM2B1A As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsulta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtDiasProrroga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiasProrroga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNvaFecRealEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNvaFecRealEntrega As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calFechaPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFechaPI As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''imgFechaPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFechaPI As Global.System.Web.UI.WebControls.Image
End Class
