'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RespuestaAforeOPI
    
    '''<summary>
    '''upnlConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlConsulta As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LblClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblClasificacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProceso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblAsterico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAsterico As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DivComboClasifOPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivComboClasifOPI As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlRespuestaAforeOPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRespuestaAforeOPI As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DivTxtClasifOPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivTxtClasifOPI As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtRespuestaAforeOPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRespuestaAforeOPI As Global.System.Web.UI.WebControls.TextBox
End Class
