'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetalleVisita
    
    '''<summary>
    '''lblFolioVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolioVisita As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPasoVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasoVisita As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Ul2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ul2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''imgSubvisitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSubvisitas As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgCancelarVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCancelarVisita As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgSolicitarProrroga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSolicitarProrroga As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgProcesoVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProcesoVisita As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''sbSubVisitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbSubVisitas As Global.SEPRIS.SubVisitas
    
    '''<summary>
    '''ccfCopiarFolios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ccfCopiarFolios As Global.SEPRIS.CopiarFolios
    
    '''<summary>
    '''idContPestanias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idContPestanias As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''tpPestaniaP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpPestaniaP As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''cuDetallePrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cuDetallePrincipal As Global.SEPRIS.cuDetalleVisita
    
    '''<summary>
    '''t_ddlAbogadoAsignado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_ddlAbogadoAsignado As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''udpAsignacionUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udpAsignacionUsuarios As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbAsignacionInspectores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAsignacionInspectores As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblTituloAbogado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloAbogado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''trRenSupTit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRenSupTit As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''trRenSupUsu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRenSupUsu As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lsbUsuariosDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbUsuariosDisponibles As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''imgAsignarSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAsignarSupervisor As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lsbSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbSupervisor As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''trRenSupFle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRenSupFle As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''imgDesasignarSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDesasignarSupervisor As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblAsignaAbogado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAsignaAbogado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbAbogadoDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbAbogadoDisponibles As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''imgAsignarAbogado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAsignarAbogado As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lsbAbogado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbAbogado As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''imgDesasignarAbogado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDesasignarAbogado As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''tbDiasTranscurridosVisitaInSitu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDiasTranscurridosVisitaInSitu As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblDiasTranscurridosVisitaInSitu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiasTranscurridosVisitaInSitu As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDiasTranscurridosDiagnosticoHallazgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDiasTranscurridosDiagnosticoHallazgos As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblDiasTranscurridosDiagnosticoHallazgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiasTranscurridosDiagnosticoHallazgos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbHallazgozInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHallazgozInt As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtEditAllazgosInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAllazgosInt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEditAllazgosInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditAllazgosInt As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''tbHallazgozExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHallazgozExt As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtEditAllazgosExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAllazgosExt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEditAllazgosExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditAllazgosExt As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''tbVulnerabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbVulnerabilidad As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtFechaVulnerabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaVulnerabilidad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ImgFecVulnerabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgFecVulnerabilidad As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''tbDiasTranscurridosPosterioresPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDiasTranscurridosPosterioresPago As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblDiasTranscurridosPosterioresPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiasTranscurridosPosterioresPago As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbAforeSolicita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAforeSolicita As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rdbRecurosRevocacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbRecurosRevocacion As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdbJuicioNulidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbJuicioNulidad As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdbNinguno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbNinguno As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblMensajeSolicitaAforeObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeSolicitaAforeObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divComentarios As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComentarios As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txbComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbComentarios As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMensajeComentarioObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeComentarioObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCarComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarComentarios As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblComentariosCaracteres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComentariosCaracteres As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgDetener control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDetener As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgNotificar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNotificar3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgGuardarCambios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGuardarCambios As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgNotificar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNotificar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAnterior As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgInicio As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgRevisarDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRevisarDocs As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgSiguiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSiguiente As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgNotificar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNotificar2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgIniciarVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIniciarVisita As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgRechazarProrroga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRechazarProrroga As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgAprobarProrroga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAprobarProrroga As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tcContPestaDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcContPestaDocs As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''tpPestaniasDocsP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpPestaniasDocsP As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''ucDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDocumentos As Global.SEPRIS.ucDocumentos
    
    '''<summary>
    '''BitacoraVisita1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BitacoraVisita1 As Global.SEPRIS.BitacoraVisita
    
    '''<summary>
    '''hfCurrentTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCurrentTab As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfFolioVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFolioVisita As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfEstaEnProrroga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEstaEnProrroga As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txbMotivoCancelacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbMotivoCancelacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ast1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ast1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Label20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCancelacionCaracteres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCancelacionCaracteres As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txbMotivoProrroga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbMotivoProrroga As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ast2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ast2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Div3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Label21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label21 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProrrogaCaracteres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProrrogaCaracteres As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgUnBotonNoAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUnBotonNoAccion As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''vsErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsErrores As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''imgDosBotonesUnaAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDosBotonesUnaAccion As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''btnAceptarM2B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarM2B1A As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelarM2B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelarM2B1A As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtFecIniVista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecIniVista As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''calExFecIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calExFecIni As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendarFecIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendarFecIni As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblErrorFecIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorFecIni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechFinVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechFinVisita As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario2 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblMensajeFechaFinVisitaObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaFinVisitaObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbRangoInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbRangoInicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txbRangoFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbRangoFin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label22 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRango control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRango As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMensajeRangoSancionObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeRangoSancionObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechaEnvioDictamen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechaEnvioDictamen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario4 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblMensajeFechaEnvioDictamenObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaEnvioDictamenObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechaPosibleEmplazamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechaPosibleEmplazamiento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender4 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario5 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblMensajeFechaPosibleEmplazamientoObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaPosibleEmplazamientoObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image8 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechaAcuseAforeRecibeOfEmpl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechaAcuseAforeRecibeOfEmpl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender5 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario6 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblMensajeFechaAcuseAforeRecibeOfEmplObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaAcuseAforeRecibeOfEmplObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image9 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechaAcuseAforeContestoOfEmpl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechaAcuseAforeContestoOfEmpl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender6 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario7 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblMensajeFechaAcuseAforeContestoOfEmplObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaAcuseAforeContestoOfEmplObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image10 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechaImposicionSancion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechaImposicionSancion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender7 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario8 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtMontoImpSan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoImpSan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtComentImpSan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComentImpSan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMensajeFechaImposicionSancionObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaImposicionSancionObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image11 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechaImposicionSancionEstimada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechaImposicionSancionEstimada As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender8 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario9 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblMensajeFechaImposicionSancionEstimadaObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaImposicionSancionEstimadaObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image12 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txbFechaAcusePagoAfore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbFechaAcusePagoAfore As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender9 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgCalendario10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendario10 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblMensajeFechaAcusePagoAforeObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeFechaAcusePagoAforeObligatorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image17 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtFechaCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaCampo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ceFechaCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ceFechaCampo As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgFechaCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFechaCampo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblFechaCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaCampo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Image15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image15 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtFechaReunion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaReunion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ceFechaReunion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ceFechaReunion As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgFechaReunion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFechaReunion As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblFechaReunion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaReunion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgProcesoInspSancion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProcesoInspSancion As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgErrorGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgErrorGeneral As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtFechaGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaGeneral As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ceFechaGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ceFechaGeneral As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''imgFechaGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFechaGeneral As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblFechaGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaGeneral As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgConfirmacion As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ValidationSummary3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary3 As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''divSubVisitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubVisitas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Image14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image14 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''chkSubVisitasMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSubVisitasMod As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''ValidationSummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary2 As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''btnPasoDiezConfSancionNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPasoDiezConfSancionNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfSanPasoSieteSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfSanPasoSieteSi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfSanPasoSieteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfSanPasoSieteNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSancionPaso8Si control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSancionPaso8Si As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSancionPaso8No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSancionPaso8No As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPasoSieteConfirmSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPasoSieteConfirmSi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPasoSieteConfirmNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPasoSieteConfirmNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso25Ok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso25Ok As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso25NoDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso25NoDos As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso32Ok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso32Ok As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso32NoDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso32NoDos As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso25 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso32 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso25Conf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso25Conf As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaPaso32Conf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaPaso32Conf As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfFechaReunionP9ok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfFechaReunionP9ok As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfFechaReunionP9NoDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfFechaReunionP9NoDos As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAlertaPaso18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlertaPaso18 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfFechaReunionVjp9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfFechaReunionVjp9 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelaFechaReunionVjp9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelaFechaReunionVjp9 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelaFechaReunionVjp16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelaFechaReunionVjp16 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelaFechaPaso25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelaFechaPaso25 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelaFechaPaso32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelaFechaPaso32 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfFechaReunionVjp16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfFechaReunionVjp16 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfFechaReunionVjpok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfFechaReunionVjpok As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfFechaReunionVjp16NoDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfFechaReunionVjp16NoDos As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaInSituActaC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaInSituActaC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaLevantaActa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaLevantaActa As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfBotonPresionado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfBotonPresionado As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubvisitasModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubvisitasModal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaCampo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaReunion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaReunion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRangoSancion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRangoSancion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRangoSancionPaso17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRangoSancionPaso17 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaAforePresi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaAforePresi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirmarDv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmarDv As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirmarNoDv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmarNoDv As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaReunionVj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaReunionVj As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFechaReunionVjP16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFechaReunionVjP16 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirmacionVulnerabilidadSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmacionVulnerabilidadSi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirmacionVulnerabilidadNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmacionVulnerabilidadNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGuardaFecVulnerabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardaFecVulnerabilidad As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelaFecVulnerabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelaFecVulnerabilidad As Global.System.Web.UI.WebControls.Button
End Class
