'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Bandeja1

   '''<summary>
   '''Ayuda control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Ayuda As Global.SEPRIS.wucAyuda

   '''<summary>
   '''imgModalPendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgModalPendientes As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''mpeProcesa control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents mpeProcesa As Global.AjaxControlToolkit.ModalPopupExtender

   '''<summary>
   '''UpdatePanel1Pendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents UpdatePanel1Pendientes As Global.System.Web.UI.UpdatePanel

   '''<summary>
   '''pnlProcesando control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlProcesando As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''Label2lblTituloPendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Label2lblTituloPendientes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''imgCierraModalPendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgCierraModalPendientes As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''btnExportaExcelPendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnExportaExcelPendientes As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''lblCriteriosDDL control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblCriteriosDDL As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblFolio control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblFolio As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''ddlFolioVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ddlFolioVisita As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''lblPasoA control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblPasoA As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''ddlPasoActual control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ddlPasoActual As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''lblPasoB control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblPasoB As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''ddlPasoActualFin control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ddlPasoActualFin As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''btnFiltrarPendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnFiltrarPendientes As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''gvConsultaPendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents gvConsultaPendientes As Global.CustomGridView.CustomGridView

   '''<summary>
   '''pnlNoExistePendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlNoExistePendientes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''Image2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''upnlConsulta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents upnlConsulta As Global.System.Web.UI.UpdatePanel

   '''<summary>
   '''pnlConsulta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlConsulta As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''lbTituloBandeja control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lbTituloBandeja As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''imgProcesoVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoVisita As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgProcesoVisitaAmbos control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoVisitaAmbos As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''btnExportaExcel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnExportaExcel As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnPersonalizaColumnas control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnPersonalizaColumnas As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''ucFiltro1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ucFiltro1 As Global.SEPRIS.ucFiltro

   '''<summary>
   '''pnlGrid control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''chkSeleccionaTodos control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents chkSeleccionaTodos As Global.System.Web.UI.WebControls.CheckBox

   '''<summary>
   '''lblSeleccionaTodos control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblSeleccionaTodos As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''gvConsulta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents gvConsulta As Global.CustomGridView.CustomGridView

   '''<summary>
   '''pnlNoExiste control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlNoExiste As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''Image1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''hfGridView1SV_gvConsulta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfGridView1SV_gvConsulta As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hfGridView1SH_gvConsulta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfGridView1SH_gvConsulta As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hfSelectedValue_gvConsulta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfSelectedValue_gvConsulta As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''Image3 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''Image4 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''Image6 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''Image5 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''btnVerReporte control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnVerReporte As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''btnRegresarBandeja control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnRegresarBandeja As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''pnlDetalle control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlDetalle As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''lblDetalle control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblDetalle As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''Label1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''btnRegresa control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnRegresa As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''imgUnBotonNoAccion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgUnBotonNoAccion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''imgProcesoVF control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoVF As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgProcesoOtras control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoOtras As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgM2B2A control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgM2B2A As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''imgUnBotonUnaAccion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgUnBotonUnaAccion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''imgDosBotonesUnaAccion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgDosBotonesUnaAccion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''Image16 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Image16 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''txtMotivoCancelacion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtMotivoCancelacion As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''lblFechaGeneral control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblFechaGeneral As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''imgProcesoInspSancion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoInspSancion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''imgProcesoInspSancionVF control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoInspSancionVF As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''imgProcesoInspSancionOtras control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoInspSancionOtras As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''btnSalirM2B2A control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSalirM2B2A As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnContinuarM2B2A control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnContinuarM2B2A As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnAceptarM1B1A control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnAceptarM1B1A As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnAceptarM2B1A control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnAceptarM2B1A As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnConsulta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnConsulta As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnConsultaPendientes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnConsultaPendientes As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnCancelarVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnCancelarVisita As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnSiRegistra control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSiRegistra As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnNoRegistra control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnNoRegistra As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''PersonalizaColumnas control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents PersonalizaColumnas As Global.SEPRIS.wucPersonalizarColumnas
End Class
