'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Vista

   '''<summary>
   '''lblFolioVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblFolioVisita As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblPasoVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblPasoVisita As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''Ul2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Ul2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''lnkTituloPag control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lnkTituloPag As Global.System.Web.UI.HtmlControls.HtmlAnchor

   '''<summary>
   '''imgProcesoVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoVisita As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgProcesoVisitaAmbos control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoVisitaAmbos As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''upTabla control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents upTabla As Global.System.Web.UI.UpdatePanel

   '''<summary>
   '''tbDatosCaptura control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tbDatosCaptura As Global.System.Web.UI.HtmlControls.HtmlTable

   '''<summary>
   '''ccfCopiarFolios control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ccfCopiarFolios As Global.SEPRIS.CopiarFolios

   '''<summary>
   '''ChkVConjunta control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ChkVConjunta As Global.System.Web.UI.WebControls.CheckBox

   '''<summary>
   '''chkListVC control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents chkListVC As Global.System.Web.UI.WebControls.CheckBoxList

   '''<summary>
   '''ejemplolabel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ejemplolabel As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txbFolioVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txbFolioVisita As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''ast1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''txbFechaRegistro control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txbFechaRegistro As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''calendarioFechaRegistro control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents calendarioFechaRegistro As Global.AjaxControlToolkit.CalendarExtender

   '''<summary>
   '''imgCalendario1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgCalendario1 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''ast2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''txbFechaInicio control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txbFechaInicio As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''calendarioFechaInicio control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents calendarioFechaInicio As Global.AjaxControlToolkit.CalendarExtender

   '''<summary>
   '''imgCalendario2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgCalendario2 As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''ast3 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''ddlTipoEntidad control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ddlTipoEntidad As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''ast9 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''dplEntidad control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dplEntidad As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''ast4 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''trSubvisitas control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents trSubvisitas As Global.System.Web.UI.HtmlControls.HtmlTableRow

   '''<summary>
   '''chkSubVisitas control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents chkSubVisitas As Global.System.Web.UI.WebControls.CheckBox

   '''<summary>
   '''trSubentidad control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents trSubentidad As Global.System.Web.UI.HtmlControls.HtmlTableRow

   '''<summary>
   '''chkSubEntidad control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents chkSubEntidad As Global.System.Web.UI.WebControls.CheckBoxList

   '''<summary>
   '''ast10 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''dplTipoVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dplTipoVisita As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''ast5 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''ast12 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast12 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''trAcuerdoVul control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents trAcuerdoVul As Global.System.Web.UI.HtmlControls.HtmlTableRow

   '''<summary>
   '''txtAcuerdoVul control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtAcuerdoVul As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''calEAcuerdoVul control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents calEAcuerdoVul As Global.AjaxControlToolkit.CalendarExtender

   '''<summary>
   '''imgAcuerdoVul control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgAcuerdoVul As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''divAcuerdoVul control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents divAcuerdoVul As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''txtOrdenVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtOrdenVisita As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''divOrdenVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents divOrdenVisita As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''SelObjetos control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents SelObjetos As Global.SEPRIS.ObjetoVisita

   '''<summary>
   '''udpAsignacionUsuarios control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents udpAsignacionUsuarios As Global.System.Web.UI.UpdatePanel

   '''<summary>
   '''tbAsignacionInspectores control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tbAsignacionInspectores As Global.System.Web.UI.HtmlControls.HtmlTable

   '''<summary>
   '''ast6 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''lsbUsuariosDisponibles control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lsbUsuariosDisponibles As Global.System.Web.UI.WebControls.ListBox

   '''<summary>
   '''imgAsignarSupervisor control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgAsignarSupervisor As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''lsbSupervisor control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lsbSupervisor As Global.System.Web.UI.WebControls.ListBox

   '''<summary>
   '''imgSubirSupervisor control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgSubirSupervisor As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgDesasignarSupervisor control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgDesasignarSupervisor As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgBajarSupervisor control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgBajarSupervisor As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''ast7 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''imgAsignarInspector control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgAsignarInspector As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''lsbInspectores control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lsbInspectores As Global.System.Web.UI.WebControls.ListBox

   '''<summary>
   '''imgSubirInspector control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgSubirInspector As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgDesasignarInspector control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgDesasignarInspector As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgBajarInspector control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgBajarInspector As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''tbAgregarOficios control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tbAgregarOficios As Global.System.Web.UI.HtmlControls.HtmlTable

   '''<summary>
   '''tblDescripcionVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tblDescripcionVisita As Global.System.Web.UI.HtmlControls.HtmlTable

   '''<summary>
   '''Label5 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txtDescripcionVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtDescripcionVisita As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''ast11 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast11 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''Div3 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''lblCarDescripcion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblCarDescripcion As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblDescripcionContador control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblDescripcionContador As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''tbComentarios control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tbComentarios As Global.System.Web.UI.HtmlControls.HtmlTable

   '''<summary>
   '''lblComentarios control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblComentarios As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txbComentarios control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txbComentarios As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''ast8 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ast8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''Div2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''lblCarComentarios control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblCarComentarios As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblComentariosCaracteres control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblComentariosCaracteres As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''Table1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

   '''<summary>
   '''imgRegistrarVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgRegistrarVisita As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgSiguiente control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgSiguiente As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgInicio control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgInicio As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''hfCurrentTab control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfCurrentTab As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hfMostrarMsg control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfMostrarMsg As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''imgUnBotonNoAccion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgUnBotonNoAccion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''vsErrores control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vsErrores As Global.System.Web.UI.WebControls.ValidationSummary

   '''<summary>
   '''imgDosBotonesUnaAccion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgDosBotonesUnaAccion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''btnAceptarM2B1A control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnAceptarM2B1A As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''imgProcesoVF control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoVF As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgProcesoOtras control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoOtras As Global.System.Web.UI.WebControls.ImageButton

   '''<summary>
   '''imgConfirmaRegistroVisita control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgConfirmaRegistroVisita As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''ValidationSummary1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

   '''<summary>
   '''imgProcesoInspSancion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoInspSancion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''imgConfirmacion control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgConfirmacion As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''ValidationSummary2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ValidationSummary2 As Global.System.Web.UI.WebControls.ValidationSummary

   '''<summary>
   '''imgHabraRevision control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgHabraRevision As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''ValidationSummary3 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ValidationSummary3 As Global.System.Web.UI.WebControls.ValidationSummary

   '''<summary>
   '''imgErrorGeneral control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgErrorGeneral As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''txtFechaGeneral control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtFechaGeneral As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''ceFechaGeneral control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ceFechaGeneral As Global.AjaxControlToolkit.CalendarExtender

   '''<summary>
   '''imgFechaGeneral control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgFechaGeneral As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''lblFechaGeneral control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblFechaGeneral As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''imgProcesoInspSancionVF control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoInspSancionVF As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''imgProcesoInspSancionOtras control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents imgProcesoInspSancionOtras As Global.System.Web.UI.WebControls.Image

   '''<summary>
   '''hfOpAct control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfOpAct As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hfOpAnt control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfOpAnt As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hfVisitaPadre control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfVisitaPadre As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''btnConfirmacionVulnerabilidadSi control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnConfirmacionVulnerabilidadSi As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnConfirmacionVulnerabilidadNo control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnConfirmacionVulnerabilidadNo As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnNoFecVulnerabilidad control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnNoFecVulnerabilidad As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnGuardaFecVulnerabilidad control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnGuardaFecVulnerabilidad As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnConfirmacionSiHabraRevision control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnConfirmacionSiHabraRevision As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnConfirmacionNoHabraRevision control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnConfirmacionNoHabraRevision As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnCancelaFecVulnerabilidad control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnCancelaFecVulnerabilidad As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''hfIdVisitaGen control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hfIdVisitaGen As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdVisitasGen control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdVisitasGen As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''BtnConfirmaRegistro control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents BtnConfirmaRegistro As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnCargaArchivo control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnCargaArchivo As Global.System.Web.UI.WebControls.Button
End Class
