'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BandejaSICOD

    '''<summary>
    '''upnlConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlConsulta As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnExportaExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportaExcel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPersonalizarColumnas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPersonalizarColumnas As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ucFiltro1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucFiltro1 As Global.SEPRIS.ucFiltro

    '''<summary>
    '''gvConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvConsulta As Global.CustomGridView.CustomGridView

    '''<summary>
    '''Noexisten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Noexisten As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''hfGridView1SV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfGridView1SV As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfGridView1SH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfGridView1SH As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSelectedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgUnBotonNoAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUnBotonNoAccion As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''vsErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsErrores As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''imgDosBotonesUnaAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDosBotonesUnaAccion As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnAceptarM1B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarM1B1A As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAceptarM2B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarM2B1A As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsulta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PersonalizaColumnas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PersonalizaColumnas As Global.SEPRIS.wucPersonalizarColumnas
End Class
