'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegistrarAgenda

    '''<summary>
    '''Ayuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ayuda As Global.SEPRIS.wucAyuda

    '''<summary>
    '''udpSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udpSolicitudes As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rblTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTipo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''csvTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTipo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''tbActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbActividad As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlTipoActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoActividad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvTipoActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTipoActividad As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''tbAusencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAusencia As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlTipoAusencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoAusencia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvTipoAusencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTipoAusencia As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''tbAutoriza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAutoriza As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlFuncionario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFuncionario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvFuncionario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFuncionario As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''tbVacaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbVacaciones As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNoHayVacaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoHayVacaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TieneVacaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TieneVacaciones As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PeriodoAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PeriodoAnterior As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPeriodoAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodoAnterior As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRestantesAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestantesAnterior As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PeriodoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PeriodoActual As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPeriodoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodoActual As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRestanteActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestanteActual As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkCiclica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCiclica As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbTiempoContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTiempoContinuo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFechaInicioContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInicioContinuo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaInicioContinuo_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInicioContinuo_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''csvFechaInicioContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFechaInicioContinuo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''imgFec1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFec1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ddlHoraInicioContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHoraInicioContinuo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvHoraInicioContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvHoraInicioContinuo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''txtFechaFinContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFinContinuo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaFinContinuo_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFinContinuo_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''csvFechaFinContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFechaFinContinuo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''imgFec2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFec2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ddlHoraFinContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHoraFinContinuo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvHoraFinContinuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvHoraFinContinuo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''tbTiempoCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTiempoCiclico As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFechaInicioCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInicioCiclico As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaInicioCiclico_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInicioCiclico_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''csvFechaInicioCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFechaInicioCiclico As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''imgFec3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFec3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtFechaFinCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFinCiclico As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaFinCiclico_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFinCiclico_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''csvFechaFinCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFechaFinCiclico As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''imgFec4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFec4 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ddlHoraInicioCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHoraInicioCiclico As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvHoraInicioCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvHoraInicioCiclico As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''ddlHoraFinCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHoraFinCiclico As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvHoraFinCiclico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvHoraFinCiclico As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''chkLunes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLunes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMartes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMartes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMiercoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMiercoles As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkJueves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkJueves As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkViernes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkViernes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDescripcionActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcionActividad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvDescripcionActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescripcionActividad As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblRestanteDescripcionActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestanteDescripcionActividad As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbNotasAutorizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNotasAutorizador As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNotasAutorizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotasAutorizador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvNotasAutorizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvNotasAutorizador As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblRestanteNotasAutorizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestanteNotasAutorizador As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnAceptar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAutorizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAutorizar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRechazar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRechazar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''imgUnBotonNoAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUnBotonNoAccion As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''vsErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsErrores As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''imgM2B2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgM2B2A As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgUnBotonUnaAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUnBotonUnaAccion As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgDosBotonesUnaAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDosBotonesUnaAccion As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnSalirM2B2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalirM2B2A As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnContinuarM2B2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinuarM2B2A As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAceptarM1B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarM1B1A As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAceptarM2B1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarM2B1A As Global.System.Web.UI.WebControls.Button
End Class
